name: Update Research Papers

on:
  schedule:
    - cron: "0 0 * * *" # Ежедневно в полночь
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update_papers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and update research papers
      run: python update_research_papers.py

    - name: Commit and push changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "GitHub Actions Bot"
        git add extra_material/research_papers.md
        git commit -m "Update research papers"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
